### All movires
GET http://localhost:1234/movies

### Getting one movie by ID
GET http://localhost:1234/movies/1

### Getting all movies by genre
GET http://localhost:1234/movies?genre=action

### Create a movie
POST http://localhost:1234/movies
Content-Type: application/json
  
  {
    "title": "The Matrix",
    "year": 1999,
    "director": "The Wachowskis",
    "duration": 136,
    "poster": "https://www.imdb.com/title/tt0133093/mediaviewer/rm4261863936",
    "genre": ["Action", "Sci-Fi"]
  }

### Update a movie
PATCH http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2000
}




### Request
GET http://localhost:1234/pokemon/ditto

### Create
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
    "transform"
  ]
}

