### All movires
GET http://localhost:1234/movies

### Getting one movie by ID
GET http://localhost:1234/movies/1

### Getting all movies by genre
GET http://localhost:1234/movies?genre=Action









### Request
GET http://localhost:1234/pokemon/ditto

### Create
POST http://localhost:1234/pokemon
Content-Type: application/json

{
  "name": "ditto",
  "type": "normal",
  "moves": [
    "transform"
  ]
}

